name: Dependency Check

concurrency:
  group: rust-dependency-check-${{ github.head_ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron:  '0 8 25 * *'

jobs:
  update_dependency:
    name: Check dependency
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update dependency
        id: update-dependency
        run: nix develop -c 'update-dependency'

      - name: Create Pull Request
        if: failure() && steps.update-dependency.outcome != 'success'
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: Cargo.toml
          reviewers: yanganto
          base: master
          branch: dependency-update
          branch-suffix: timestamp
          title: "Dependency Update"
          commit-message: "automated dependency update"
